version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - mynet
  
  rest_server:
    build: .
    command: python ./server/rest_server.py
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - mynet

  rest_client:
    build: .
    command: python ./client/rest_client.py
    depends_on:
      - rest_server
    networks:
      - mynet

volumes:
  db_data:

networks:
  mynet:
