version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
  
  rest_server:
    build: .
    command: python rest_server.py
    ports:
      - "3000:3000"

  # rest_client:
  #   build: .
  #   command: python rest_client.py

volumes:
  db_data:
