# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x07message\">\n\x0eMessageRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x0e\n\x06system\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\x08\"!\n\x0fMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2R\n\x0eMessageService\x12@\n\x0bSendMessage\x12\x17.message.MessageRequest\x1a\x18.message.MessageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGEREQUEST']._serialized_start=26
  _globals['_MESSAGEREQUEST']._serialized_end=88
  _globals['_MESSAGERESPONSE']._serialized_start=90
  _globals['_MESSAGERESPONSE']._serialized_end=123
  _globals['_MESSAGESERVICE']._serialized_start=125
  _globals['_MESSAGESERVICE']._serialized_end=207
# @@protoc_insertion_point(module_scope)
